common: &common
  bucket: bucket_dev
  access_key_id: AKIAIB2GYPDWTBK6FXTQ
  secret_access_key: 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
development:
  <<: *common
test:
  <<: *common
  bucket: lawdingo_test
staging:
  <<: *common
  bucket: lawdingo_staging
production:
  <<: *common
  bucket: bucket_pro